version: "3.8"

services:
  backend-app:
    build:
      context: .
    container_name: fastapi-app
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - "9000:8000"
    depends_on:
      - backend-cron  # Ensure the cron service is ready before starting the app

  backend-cron:
    build:
      context: .
    container_name: cron-python
    command: sh -c "cron && tail -f /var/log/cnbc_cron.log /var/log/news_cron.log"
    env_file:
      - .env
