"""v26_update_assessment_table

Revision ID: 02ffab7e730c
Revises: b67c03e025d2
Create Date: 2024-12-02 15:52:21.127238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ffab7e730c'
down_revision: Union[str, None] = 'b67c03e025d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('capital_assessment', sa.JSON(), nullable=True))
    op.add_column('assessments', sa.Column('dividend_assessment', sa.JSON(), nullable=True))
    op.add_column('assessments', sa.Column('earnings_assessment', sa.JSON(), nullable=True))
    op.add_column('assessments', sa.Column('receivables_assessment', sa.JSON(), nullable=True))
    op.add_column('assessments', sa.Column('valuation_assessment', sa.JSON(), nullable=True))
    op.add_column('assessments', sa.Column('miscellaneous_assessment', sa.JSON(), nullable=True))
    op.add_column('assessments', sa.Column('other_assessment', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'other_assessment')
    op.drop_column('assessments', 'miscellaneous_assessment')
    op.drop_column('assessments', 'valuation_assessment')
    op.drop_column('assessments', 'receivables_assessment')
    op.drop_column('assessments', 'earnings_assessment')
    op.drop_column('assessments', 'dividend_assessment')
    op.drop_column('assessments', 'capital_assessment')
    # ### end Alembic commands ###
