"""v19_update_news_table

Revision ID: 0d2ffea69fd0
Revises: cb1736471128
Create Date: 2024-11-18 17:46:55.117529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2ffea69fd0'
down_revision: Union[str, None] = 'cb1736471128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_items', sa.Column('small_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_items', 'small_description')
    # ### end Alembic commands ###
