"""v9_added_new_field_in_ratio_table

Revision ID: 123d98a8ef12
Revises: 7bd87c0a7e3b
Create Date: 2024-10-18 15:32:53.427112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '123d98a8ef12'
down_revision: Union[str, None] = '7bd87c0a7e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratios', sa.Column('nifty_sahre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratios', 'nifty_sahre')
    # ### end Alembic commands ###
