"""v3_create_newssave_model

Revision ID: 1cb8206cc9f0
Revises: c3de0513509d
Create Date: 2024-10-16 09:12:31.549699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb8206cc9f0'
down_revision: Union[str, None] = 'c3de0513509d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_saves',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('news_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_saves_news_id'), 'news_saves', ['news_id'], unique=False)
    op.create_index(op.f('ix_news_saves_user_id'), 'news_saves', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_saves_user_id'), table_name='news_saves')
    op.drop_index(op.f('ix_news_saves_news_id'), table_name='news_saves')
    op.drop_table('news_saves')
    # ### end Alembic commands ###
