"""Adding tour steps for user

Revision ID: 26e902fdc1f0
Revises: 627f78e79801
Create Date: 2025-03-27 17:19:04.627684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26e902fdc1f0'
down_revision: Union[str, None] = '627f78e79801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SequelizeMeta')
    op.drop_table('otps')
    op.add_column('users', sa.Column('tour_taken', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('tour_step', sa.INTEGER(), nullable=True))
    op.drop_column('users', 'googleId')
    op.drop_column('users', 'otp_attempts')
    op.drop_column('users', 'otp_last_attempt_at')
    op.drop_column('users', 'loginType')
    op.drop_constraint('fk_watchlists_company_id', 'watchlists', type_='foreignkey')
    op.drop_column('watchlists', 'companyId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('companyId', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_watchlists_company_id', 'watchlists', 'companies', ['companyId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('users', sa.Column('loginType', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('otp_last_attempt_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('otp_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('googleId', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'tour_step')
    op.drop_column('users', 'tour_taken')
    op.create_table('otps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('otp', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='otps_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='otps_pkey')
    )
    op.create_table('SequelizeMeta',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='SequelizeMeta_pkey')
    )
    # ### end Alembic commands ###
