"""v23_update_ratio_table

Revision ID: 2aeb5458f2d8
Revises: ad7f0b7c4a20
Create Date: 2024-11-28 14:25:55.142882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2aeb5458f2d8'
down_revision: Union[str, None] = 'ad7f0b7c4a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'share_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'current_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'share_symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'share_price',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'market_cap',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'high_low',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'pe_ratio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'enterprise_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'book_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'dividend_yield',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'promoter_holding',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'eps',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'sales_growth',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'profit_growth',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'roce',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'cash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'debt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'roe',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'face_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'bse',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'nse',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'chart',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('companies', 's_pros',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 's_cons',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 's_peer_comparison',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('companies', 's_quarterly_results',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('companies', 's_profit_loss',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('companies', 's_balance_sheet',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('companies', 's_cash_flows',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('companies', 's_ratios',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('companies', 's_shareholding_pattern_quarterly',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('companies', 's_shareholding_pattern_yearly',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('companies', 's_documents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('companies', 't_strengths',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 't_limitations',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 't_quarterly_results',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('companies', 't_profit_loss',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('companies', 't_balance_sheet_equity_and_liabilities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('companies', 't_balance_sheet_assets',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('companies', 't_cash_flows',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 't_cash_flows',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('companies', 't_balance_sheet_assets',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('companies', 't_balance_sheet_equity_and_liabilities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('companies', 't_profit_loss',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('companies', 't_quarterly_results',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('companies', 't_limitations',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 't_strengths',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 's_documents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('companies', 's_shareholding_pattern_yearly',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('companies', 's_shareholding_pattern_quarterly',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('companies', 's_ratios',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('companies', 's_cash_flows',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('companies', 's_balance_sheet',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('companies', 's_profit_loss',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('companies', 's_quarterly_results',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('companies', 's_peer_comparison',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('companies', 's_cons',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 's_pros',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'chart',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('companies', 'nse',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'bse',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'face_value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'roe',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'debt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'cash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'roce',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'profit_growth',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'sales_growth',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'eps',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'promoter_holding',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'dividend_yield',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'book_value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'enterprise_value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'pe_ratio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'high_low',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'market_cap',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'share_price',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'share_symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'current_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'share_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
