"""v11_update_user_table

Revision ID: 35b2d0ff00fe
Revises: 56c422bcac8e
Create Date: 2024-10-21 14:48:48.154141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b2d0ff00fe'
down_revision: Union[str, None] = '56c422bcac8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('divece', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'divece')
    # ### end Alembic commands ###
