"""v21_added_calculate_ratio_table

Revision ID: 4700d070bcdf
Revises: 75518c3202e6
Create Date: 2024-11-27 09:59:52.156702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4700d070bcdf'
down_revision: Union[str, None] = '75518c3202e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculate_ratios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('liquidity_ratio', sa.JSON(), nullable=False),
    sa.Column('solvency_ratio', sa.JSON(), nullable=False),
    sa.Column('efficiency_ratio', sa.JSON(), nullable=False),
    sa.Column('growth_ratio', sa.JSON(), nullable=False),
    sa.Column('coverage_ratio', sa.JSON(), nullable=False),
    sa.Column('financial_ratio', sa.JSON(), nullable=False),
    sa.Column('profitability_ratio', sa.JSON(), nullable=False),
    sa.Column('valuation_ratios', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculate_ratios_company_id'), 'calculate_ratios', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculate_ratios_company_id'), table_name='calculate_ratios')
    op.drop_table('calculate_ratios')
    # ### end Alembic commands ###
