"""watchlist added

Revision ID: 627f78e79801
Revises: 9c24bf542118
Create Date: 2024-12-23 15:33:27.257640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627f78e79801'
down_revision: Union[str, None] = '9c24bf542118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('company_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.add_column('companies', sa.Column('share_price_percentage', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('industry_pe', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('sectore_pe', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('pb_ratio', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('average_pe', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'average_pe')
    op.drop_column('companies', 'pb_ratio')
    op.drop_column('companies', 'sectore_pe')
    op.drop_column('companies', 'industry_pe')
    op.drop_column('companies', 'share_price_percentage')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    # ### end Alembic commands ###
