"""v24_added_assessment_table

Revision ID: 6434c688a80f
Revises: 2aeb5458f2d8
Create Date: 2024-12-02 11:40:00.056364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6434c688a80f'
down_revision: Union[str, None] = '2aeb5458f2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('share_symbol', sa.String(), nullable=True),
    sa.Column('management_assessment', sa.JSON(), nullable=True),
    sa.Column('liquidity_assessment', sa.JSON(), nullable=True),
    sa.Column('debt_assessment', sa.JSON(), nullable=True),
    sa.Column('equity_assessment', sa.JSON(), nullable=True),
    sa.Column('revenue_assessment', sa.JSON(), nullable=True),
    sa.Column('cost_assessment', sa.JSON(), nullable=True),
    sa.Column('operational_assessment', sa.JSON(), nullable=True),
    sa.Column('risk_assessment', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_company_id'), 'assessments', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessments_company_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
