"""Added flag column to Chat table

Revision ID: 673ade9106d2
Revises: 3b0108b40848
Create Date: 2025-04-04 12:52:54.285476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '673ade9106d2'
down_revision: Union[str, None] = '3b0108b40848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('flag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'flag')
    # ### end Alembic commands ###
