"""v2_update_news_table

Revision ID: 6b46018dfe5b
Revises: c0d9760de773
Create Date: 2024-09-19 16:47:46.270372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b46018dfe5b'
down_revision: Union[str, None] = 'c0d9760de773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_items', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('news_items', sa.Column('stock_name', sa.String(), nullable=True))
    op.add_column('news_items', sa.Column('sectors', sa.String(), nullable=True))
    op.add_column('news_items', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('news_items', 'user_search')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_items', sa.Column('user_search', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('news_items', 'category')
    op.drop_column('news_items', 'sectors')
    op.drop_column('news_items', 'stock_name')
    op.drop_column('news_items', 'company_name')
    # ### end Alembic commands ###
