"""v20_added_company_table

Revision ID: 75518c3202e6
Revises: 0d2ffea69fd0
Create Date: 2024-11-21 14:06:59.012486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75518c3202e6'
down_revision: Union[str, None] = '0d2ffea69fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('share_name', sa.String(), nullable=False),
    sa.Column('current_date', sa.String(), nullable=False),
    sa.Column('share_symbol', sa.String(), nullable=False),
    sa.Column('share_price', sa.String(), nullable=False),
    sa.Column('market_cap', sa.String(), nullable=False),
    sa.Column('high_low', sa.String(), nullable=False),
    sa.Column('pe_ratio', sa.String(), nullable=False),
    sa.Column('enterprise_value', sa.String(), nullable=False),
    sa.Column('book_value', sa.String(), nullable=False),
    sa.Column('dividend_yield', sa.String(), nullable=False),
    sa.Column('promoter_holding', sa.String(), nullable=False),
    sa.Column('eps', sa.String(), nullable=False),
    sa.Column('sales_growth', sa.String(), nullable=False),
    sa.Column('profit_growth', sa.String(), nullable=False),
    sa.Column('roce', sa.String(), nullable=False),
    sa.Column('cash', sa.String(), nullable=False),
    sa.Column('debt', sa.String(), nullable=False),
    sa.Column('roe', sa.String(), nullable=False),
    sa.Column('face_value', sa.String(), nullable=False),
    sa.Column('bse', sa.String(), nullable=False),
    sa.Column('nse', sa.String(), nullable=False),
    sa.Column('chart', sa.JSON(), nullable=False),
    sa.Column('s_pros', sa.String(), nullable=False),
    sa.Column('s_cons', sa.String(), nullable=False),
    sa.Column('s_peer_comparison', sa.JSON(), nullable=False),
    sa.Column('s_quarterly_results', sa.JSON(), nullable=False),
    sa.Column('s_profit_loss', sa.JSON(), nullable=False),
    sa.Column('s_balance_sheet', sa.JSON(), nullable=False),
    sa.Column('s_cash_flows', sa.JSON(), nullable=False),
    sa.Column('s_ratios', sa.JSON(), nullable=False),
    sa.Column('s_shareholding_pattern_quarterly', sa.JSON(), nullable=False),
    sa.Column('s_shareholding_pattern_yearly', sa.JSON(), nullable=False),
    sa.Column('s_documents', sa.JSON(), nullable=False),
    sa.Column('t_strengths', sa.String(), nullable=False),
    sa.Column('t_limitations', sa.String(), nullable=False),
    sa.Column('t_quarterly_results', sa.JSON(), nullable=False),
    sa.Column('t_profit_loss', sa.JSON(), nullable=False),
    sa.Column('t_balance_sheet_equity_and_liabilities', sa.JSON(), nullable=False),
    sa.Column('t_balance_sheet_assets', sa.JSON(), nullable=False),
    sa.Column('t_cash_flows', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###
