"""v8_update_user_model

Revision ID: 7bd87c0a7e3b
Revises: c26a150d5184
Create Date: 2024-10-18 12:49:37.101962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd87c0a7e3b'
down_revision: Union[str, None] = 'c26a150d5184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_social', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_social')
    op.drop_column('users', 'firebase_id')
    # ### end Alembic commands ###
