"""create company50 table

Revision ID: 9141f455673e
Revises: 3feb674c3022
Create Date: 2025-04-17 11:55:47.100686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9141f455673e'
down_revision: Union[str, None] = '3feb674c3022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company50',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('share_name', sa.String(), nullable=True),
    sa.Column('current_date', sa.String(), nullable=True),
    sa.Column('share_symbol', sa.String(), nullable=True),
    sa.Column('share_price', sa.String(), nullable=True),
    sa.Column('compnay_info_doc', sa.String(), nullable=True),
    sa.Column('share_price_percentage', sa.String(), nullable=True),
    sa.Column('industry_pe', sa.String(), nullable=True),
    sa.Column('sectore_pe', sa.String(), nullable=True),
    sa.Column('market_cap', sa.String(), nullable=True),
    sa.Column('high_low', sa.String(), nullable=True),
    sa.Column('pe_ratio', sa.String(), nullable=True),
    sa.Column('pb_ratio', sa.String(), nullable=True),
    sa.Column('average_pe', sa.String(), nullable=True),
    sa.Column('sectore', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('enterprise_value', sa.String(), nullable=True),
    sa.Column('book_value', sa.String(), nullable=True),
    sa.Column('dividend_yield', sa.String(), nullable=True),
    sa.Column('promoter_holding', sa.String(), nullable=True),
    sa.Column('eps', sa.String(), nullable=True),
    sa.Column('sales_growth', sa.String(), nullable=True),
    sa.Column('profit_growth', sa.String(), nullable=True),
    sa.Column('roce', sa.String(), nullable=True),
    sa.Column('cash', sa.String(), nullable=True),
    sa.Column('debt', sa.String(), nullable=True),
    sa.Column('roe', sa.String(), nullable=True),
    sa.Column('face_value', sa.String(), nullable=True),
    sa.Column('bse', sa.String(), nullable=True),
    sa.Column('nse', sa.String(), nullable=True),
    sa.Column('chart', sa.JSON(), nullable=True),
    sa.Column('s_pros', sa.String(), nullable=True),
    sa.Column('s_cons', sa.String(), nullable=True),
    sa.Column('s_peer_comparison', sa.JSON(), nullable=True),
    sa.Column('s_quarterly_results', sa.JSON(), nullable=True),
    sa.Column('s_profit_loss', sa.JSON(), nullable=True),
    sa.Column('s_balance_sheet', sa.JSON(), nullable=True),
    sa.Column('s_cash_flows', sa.JSON(), nullable=True),
    sa.Column('s_ratios', sa.JSON(), nullable=True),
    sa.Column('s_shareholding_pattern_quarterly', sa.JSON(), nullable=True),
    sa.Column('s_shareholding_pattern_yearly', sa.JSON(), nullable=True),
    sa.Column('s_documents', sa.JSON(), nullable=True),
    sa.Column('t_strengths', sa.String(), nullable=True),
    sa.Column('t_limitations', sa.String(), nullable=True),
    sa.Column('t_quarterly_results', sa.JSON(), nullable=True),
    sa.Column('t_profit_loss', sa.JSON(), nullable=True),
    sa.Column('t_balance_sheet_equity_and_liabilities', sa.JSON(), nullable=True),
    sa.Column('t_balance_sheet_assets', sa.JSON(), nullable=True),
    sa.Column('t_cash_flows', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company50')
    # ### end Alembic commands ###
