"""v3_add_new_field_in_news_table

Revision ID: 97472d6f7a10
Revises: 6b46018dfe5b
Create Date: 2024-10-09 15:30:03.475934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97472d6f7a10'
down_revision: Union[str, None] = '6b46018dfe5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_items', sa.Column('published_date', sa.String(), nullable=True))
    op.add_column('news_items', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('news_items', sa.Column('classification', sa.String(), nullable=True))
    op.add_column('news_items', sa.Column('type_of_impact', sa.String(), nullable=True))
    op.add_column('news_items', sa.Column('Country', sa.String(), nullable=True))
    op.add_column('news_items', sa.Column('scale_of_impact', sa.String(), nullable=True))
    op.add_column('news_items', sa.Column('timeframe_of_impact', sa.String(), nullable=True))
    op.add_column('news_items', sa.Column('investor_sentiment', sa.String(), nullable=True))
    op.add_column('news_items', sa.Column('market_volatility', sa.String(), nullable=True))
    op.add_column('news_items', sa.Column('detailed_explanation', sa.String(), nullable=True))
    op.add_column('news_items', sa.Column('other_news_link', sa.String(), nullable=True))
    op.drop_column('news_items', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_items', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('news_items', 'other_news_link')
    op.drop_column('news_items', 'detailed_explanation')
    op.drop_column('news_items', 'market_volatility')
    op.drop_column('news_items', 'investor_sentiment')
    op.drop_column('news_items', 'timeframe_of_impact')
    op.drop_column('news_items', 'scale_of_impact')
    op.drop_column('news_items', 'Country')
    op.drop_column('news_items', 'type_of_impact')
    op.drop_column('news_items', 'classification')
    op.drop_column('news_items', 'summary')
    op.drop_column('news_items', 'published_date')
    # ### end Alembic commands ###
