"""v12_update_user_table

Revision ID: 9813ef07dc9e
Revises: 35b2d0ff00fe
Create Date: 2024-10-21 14:54:59.512772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9813ef07dc9e'
down_revision: Union[str, None] = '35b2d0ff00fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device', sa.String(), nullable=True))
    op.drop_column('users', 'divece')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('divece', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'device')
    # ### end Alembic commands ###
