"""v27_update_ratio_table

Revision ID: 9c24bf542118
Revises: 02ffab7e730c
Create Date: 2024-12-04 15:31:41.086486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c24bf542118'
down_revision: Union[str, None] = '02ffab7e730c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratios', sa.Column('company_id', sa.String(), nullable=True))
    op.add_column('ratios', sa.Column('share_symbol', sa.String(), nullable=True))
    op.add_column('ratios', sa.Column('liquidity_ratio', sa.JSON(), nullable=True))
    op.add_column('ratios', sa.Column('solvency_ratio', sa.JSON(), nullable=True))
    op.add_column('ratios', sa.Column('efficiency_ratio', sa.JSON(), nullable=True))
    op.add_column('ratios', sa.Column('growth_ratio', sa.JSON(), nullable=True))
    op.add_column('ratios', sa.Column('coverage_ratio', sa.JSON(), nullable=True))
    op.add_column('ratios', sa.Column('financial_ratio', sa.JSON(), nullable=True))
    op.add_column('ratios', sa.Column('profitability_ratio', sa.JSON(), nullable=True))
    op.add_column('ratios', sa.Column('valuation_ratios', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_ratios_company_id'), 'ratios', ['company_id'], unique=False)
    op.create_foreign_key(None, 'ratios', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ratios', 'conclusion')
    op.drop_column('ratios', 'financial_ratio_analysis')
    op.drop_column('ratios', 'nifty_sahre')
    op.drop_column('ratios', 'key_highlights')
    op.drop_column('ratios', 'stock_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratios', sa.Column('stock_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ratios', sa.Column('key_highlights', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ratios', sa.Column('nifty_sahre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ratios', sa.Column('financial_ratio_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ratios', sa.Column('conclusion', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ratios', type_='foreignkey')
    op.drop_index(op.f('ix_ratios_company_id'), table_name='ratios')
    op.drop_column('ratios', 'valuation_ratios')
    op.drop_column('ratios', 'profitability_ratio')
    op.drop_column('ratios', 'financial_ratio')
    op.drop_column('ratios', 'coverage_ratio')
    op.drop_column('ratios', 'growth_ratio')
    op.drop_column('ratios', 'efficiency_ratio')
    op.drop_column('ratios', 'solvency_ratio')
    op.drop_column('ratios', 'liquidity_ratio')
    op.drop_column('ratios', 'share_symbol')
    op.drop_column('ratios', 'company_id')
    # ### end Alembic commands ###
