"""v16_update_ratio_table

Revision ID: a061b43492aa
Revises: 784f27ccd998
Create Date: 2024-11-11 14:25:28.766933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a061b43492aa'
down_revision: Union[str, None] = '784f27ccd998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratios', sa.Column('financial_ratio_analysis', sa.JSON(), nullable=True))
    op.add_column('ratios', sa.Column('key_highlights', sa.JSON(), nullable=True))
    op.add_column('ratios', sa.Column('stock_valuation', sa.String(), nullable=True))
    op.add_column('ratios', sa.Column('conclusion', sa.JSON(), nullable=True))
    op.drop_column('ratios', 'favourable_indicators')
    op.drop_column('ratios', 'unfavourable_indicators')
    op.drop_column('ratios', 'cons')
    op.drop_column('ratios', 'summary')
    op.drop_column('ratios', 'stock_name')
    op.drop_column('ratios', 'investment_recommendation')
    op.drop_column('ratios', 'pros')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratios', sa.Column('pros', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ratios', sa.Column('investment_recommendation', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ratios', sa.Column('stock_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ratios', sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ratios', sa.Column('cons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ratios', sa.Column('unfavourable_indicators', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ratios', sa.Column('favourable_indicators', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('ratios', 'conclusion')
    op.drop_column('ratios', 'stock_valuation')
    op.drop_column('ratios', 'key_highlights')
    op.drop_column('ratios', 'financial_ratio_analysis')
    # ### end Alembic commands ###
