"""v22_update_ratio_table

Revision ID: ad7f0b7c4a20
Revises: 4700d070bcdf
Create Date: 2024-11-27 18:42:04.226158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7f0b7c4a20'
down_revision: Union[str, None] = '4700d070bcdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculate_ratios', sa.Column('share_symbol', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('compnay_info_doc', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('sectore', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('industry', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'industry')
    op.drop_column('companies', 'sectore')
    op.drop_column('companies', 'compnay_info_doc')
    op.drop_column('calculate_ratios', 'share_symbol')
    # ### end Alembic commands ###
