"""v4_update_field_in_news_table

Revision ID: b034e3ae0efc
Revises: 97472d6f7a10
Create Date: 2024-10-09 15:42:41.721064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b034e3ae0efc'
down_revision: Union[str, None] = '97472d6f7a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
