"""v25_update_assessment_table

Revision ID: b67c03e025d2
Revises: 6434c688a80f
Create Date: 2024-12-02 14:54:09.889004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67c03e025d2'
down_revision: Union[str, None] = '6434c688a80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('assessments', sa.Column('flag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'flag')
    op.drop_column('assessments', 'summary')
    # ### end Alembic commands ###
