"""v1_create_news_table

Revision ID: c0d9760de773
Revises: 
Create Date: 2024-09-18 15:05:46.950970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d9760de773'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_search', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('time_to_out_news', sa.String(), nullable=True),
    sa.Column('feed', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('similar', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_items')
    # ### end Alembic commands ###
