"""v7_update_ratio_model

Revision ID: c26a150d5184
Revises: c6feda978224
Create Date: 2024-10-18 11:11:21.757976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26a150d5184'
down_revision: Union[str, None] = 'c6feda978224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratios', sa.Column('pros', sa.JSON(), nullable=True))
    op.add_column('ratios', sa.Column('cons', sa.JSON(), nullable=True))
    op.drop_column('ratios', 'ai_pros')
    op.drop_column('ratios', 'ai_cons')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratios', sa.Column('ai_cons', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ratios', sa.Column('ai_pros', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ratios', 'cons')
    op.drop_column('ratios', 'pros')
    # ### end Alembic commands ###
