"""v6_create_ration_tabke

Revision ID: c6feda978224
Revises: b1416ad5c20a
Create Date: 2024-10-17 14:11:53.040628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6feda978224'
down_revision: Union[str, None] = 'b1416ad5c20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stock_name', sa.String(), nullable=True),
    sa.Column('favourable_indicators', sa.JSON(), nullable=True),
    sa.Column('unfavourable_indicators', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('ai_pros', sa.String(), nullable=True),
    sa.Column('ai_cons', sa.String(), nullable=True),
    sa.Column('investment_recommendation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_table('ratios')
    # ### end Alembic commands ###
