"""v28_update_company_table

Revision ID: c93da453c4de
Revises: 9c24bf542118
Create Date: 2024-12-10 14:18:44.666597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c93da453c4de'
down_revision: Union[str, None] = '9c24bf542118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_name')
    op.add_column('companies', sa.Column('pb_ratio', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('average_pe', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'average_pe')
    op.drop_column('companies', 'pb_ratio')
    op.create_table('table_name',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('share_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('share_symbol', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('share_price', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('market_cap', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('high_low', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pe_ratio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('enterprise_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('book_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dividend_yield', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('promoter_holding', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('eps', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sales_growth', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profit_growth', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('roce', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('debt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('roe', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('face_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chart', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('s_pros', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('s_cons', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('s_peer_comparison', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('s_quarterly_results', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('s_profit_loss', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('s_balance_sheet', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('s_cash_flows', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('s_ratios', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('s_shareholding_pattern_quarterly', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('s_shareholding_pattern_yearly', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('s_documents', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('t_strengths', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('t_limitations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('t_quarterly_results', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('t_profit_loss', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('t_balance_sheet_equity_and_liabilities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('t_balance_sheet_assets', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('t_cash_flows', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('compnay_info_doc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sectore', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
