"""v18_update_chat_table

Revision ID: cb1736471128
Revises: e916ac73d008
Create Date: 2024-11-12 10:09:59.834272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1736471128'
down_revision: Union[str, None] = 'e916ac73d008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('session_id', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('content_topic', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'url')
    op.drop_column('chats', 'filename')
    op.drop_column('chats', 'content_topic')
    op.drop_column('chats', 'session_id')
    # ### end Alembic commands ###
