"""v1_init_commit

Revision ID: d471da681dea
Revises: 
Create Date: 2024-10-11 17:58:30.980419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd471da681dea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('published_date', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('type_of_impact', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sectors', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('Country', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('stock_name', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('scale_of_impact', sa.String(), nullable=True),
    sa.Column('timeframe_of_impact', sa.String(), nullable=True),
    sa.Column('investor_sentiment', sa.String(), nullable=True),
    sa.Column('market_volatility', sa.String(), nullable=True),
    sa.Column('detailed_explanation', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('time_to_out_news', sa.String(), nullable=True),
    sa.Column('feed', sa.String(), nullable=True),
    sa.Column('other_news_link', sa.String(), nullable=True),
    sa.Column('similar', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('providers', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('email_otps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('otp', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_otps_user_id'), 'email_otps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_otps_user_id'), table_name='email_otps')
    op.drop_table('email_otps')
    op.drop_table('users')
    op.drop_table('news_items')
    # ### end Alembic commands ###
