"""v17_update_ratio_table

Revision ID: e916ac73d008
Revises: a061b43492aa
Create Date: 2024-11-11 14:32:05.714926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e916ac73d008'
down_revision: Union[str, None] = 'a061b43492aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratios', sa.Column('stock_value', sa.JSON(), nullable=True))
    op.drop_column('ratios', 'stock_valuation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratios', sa.Column('stock_valuation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ratios', 'stock_value')
    # ### end Alembic commands ###
