"""v29_update_company_table

Revision ID: f322e458153c
Revises: c93da453c4de
Create Date: 2024-12-11 17:07:36.706256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f322e458153c'
down_revision: Union[str, None] = 'c93da453c4de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('share_price_percentage', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('industry_pe', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('sectore_pe', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'sectore_pe')
    op.drop_column('companies', 'industry_pe')
    op.drop_column('companies', 'share_price_percentage')
    # ### end Alembic commands ###
