import asyncio
import io
import os
import tiktoken
import httpx
# import pymupdf
import logging
# import openai
import time
import random
import fitz
import google.generativeai as genai
from dotenv import load_dotenv
# from concurrent.futures import ThreadPoolExecutor

gemini_keys = [
    "GEMINI_API_KEY_11",
    "GEMINI_API_KEY_12",
    "GEMINI_API_KEY_13",
    "GEMINI_API_KEY_14",
    "GEMINI_API_KEY_15",
    "GEMINI_API_KEY_16",
    "GEMINI_API_KEY_17",
    "GEMINI_API_KEY_18",
    "GEMINI_API_KEY_19",
    "GEMINI_API_KEY_20"
]

def get_random_key_name():
    return random.choice(gemini_keys)

async def run_sync_in_thread(func, *args, **kwargs):
    loop = asyncio.get_running_loop()
    from functools import partial
    func_call = partial(func, *args, **kwargs)
    return await loop.run_in_executor(None, func_call)


def _sync_extract_text_content(input_binary):
    try:
        with io.BytesIO(input_binary) as pdf_file:
            doc = fitz.open(stream=pdf_file, filetype="pdf")
            text = "\n".join([page.get_text("text") for page in doc])
            doc.close()
            return text
    except Exception as e:
        logging.critical(f"Unable to open or process the PDF file content: {e}")
        return None
    

def _sync_generate_content(model_name, prompt_string):
    """Synchronous call to Gemini API."""
    try:
        gemini_ai_key = os.getenv(get_random_key_name())
        if not gemini_ai_key:
            logging.error(f"Gemini API key (tried {get_random_key_name()}) not found in environment.")
            return "[ERROR: API key not configured]"
        genai.configure(api_key=gemini_ai_key)
        model_instance = genai.GenerativeModel(model_name)
        response = model_instance.generate_content(prompt_string)
        # Consider adding more robust checking of the response object
        # E.g., check response.prompt_feedback for block reasons
        if not response.parts:
             # Handle cases where generation might be blocked or return empty
             feedback = getattr(response, 'prompt_feedback', None)
             block_reason = getattr(feedback, 'block_reason', 'Unknown')
             safety_ratings = getattr(feedback, 'safety_ratings', 'N/A')
             logging.warning(f"Gemini returned no content. Block Reason: {block_reason}, Safety Ratings: {safety_ratings}")
             return f"[ERROR: Gemini generation failed or blocked - Reason: {block_reason}]"
        return response.text
    except Exception as e:
        logging.error(f"Gemini API call failed for model {model_name}: {e}", exc_info=True)
        return f"[ERROR: Gemini API call failed - {e}]"

async def improver(input_text):
    prompt4 = (
      "You are a highly skilled Financial Assistant LLM designed to refine and enhance financial reports generated by other LLMs. "
      "Your task is to strictly follow the output structure and formatting rules given below. "
      "⚠️ The output of this LLM will be directly served to end users, so it must be clean, polished, and in proper **Markdown format**. "
      "if the document doesn't contain financial information or if given input is not a report from financial annual report, you should return a message saying **'this document doesn't contain required financial information'** "
      "Do **not** use code block formatting like ``` or ```html under any circumstance.\n\n"
      "If the input only contains the structure of the expected output, but all fields are either empty or contain only placeholders, return: 'This document doesn't contain the required financial information.'"

      "**Output Format:**\n"
      "# 📊 [Company Name]\n"
      "Try to fetch the company name from the document. If the name is not available, use: 'Company Information'.\n\n"

      "## 💰 Summary\n"
      "- Provide a concise, data-backed summary in bullet points.\n"
      "- Every point must reference specific financial figures or performance trends.\n\n"

      "## 💰 Financial Health\n"
      "- Analyze financial strength, profitability, risks, and trends.\n"
      "- Justify all insights with extracted data.\n\n"

      "## 📈 Investment Insights\n"
      "- Highlight opportunities and risks for investors.\n"
      "- Support all statements with financial reasoning (e.g., trends, ratios, earnings).\n\n"

      "## 📊 Key Financial Metrics\n"
      "| 📌 Metric | 📉 Value | 📋 Explanation |\n"
      "|----------|---------|---------------|\n"
      "| Revenue | [Value] | [Explanation] |\n"
      "| Net Profit | [Value] | [Explanation] |\n"
      "| EPS | [Value] | [Explanation] |\n"
      "[Add only rows with available data. If no metrics are available, remove the entire table.]\n\n"

      "## 📊 Comparative Analysis\n"
      "- Compare financial performance over available time periods.\n"
      "- Use only internal company data (no industry comparisons).\n"
      "- If insufficient data is present, omit this section.\n\n"

      "## 🔮 Predictive Analysis\n"
      "| 🔍 Metric | 📈 Last Reported Value | 📊 Forecasted Next Value | 🔎 Prediction Rationale |\n"
      "|----------|------------------------|--------------------------|--------------------------|\n"
      "| Revenue | [Value] | [Predicted Value] | [Reasoning] |\n"
      "| EPS | [Value] | [Predicted Value] | [Reasoning] |\n"
      "[Only include rows where a logical prediction can be made. If data is insufficient, remove the table.]\n\n"

      "_This report is for informational purposes only and should not be considered as investment advice. Investors should conduct their own research and consult with a financial advisor before making investment decisions._\n\n"

      "🚫 **Strict Prohibitions:**\n"
      "- Do NOT use code blocks such as ``` or ```html. These are strictly prohibited.\n"
      "- Do NOT include any empty tables or sections. If data is unavailable, remove the entire table or section.\n"
      "- Do NOT output placeholders or gibberish like 'fmhgbdlmbhdf'.\n"
      "- Do NOT use assistant-style phrases like:\n"
      "  * 'Here’s the report based on your input'\n"
      "  * 'Sure! Here's an improved version'\n"
      "  * 'Let me know if you want changes'\n"
       "should not inclue conversational text such as 'Here's a structured company insight report based on the provided financial data'"
       "avoid all the conversational lines such as 'okay now i understand here is the generated report'"
      "- Do NOT include any apologies, [ERROR] messages, or references to missing data.\n\n"

      "✅ **Correct Formatting Example:**\n"
      "  - The company turned profitable, reporting a profit after tax of <font color='green'>1,455.36</font> lakhs for FY 2017-18 compared to a loss of <font color='red'>512.01</font> lakhs in FY 2016-17.\n"
      "❌ **Incorrect Formatting Example:**\n"
      "  - The company turned profitable, reporting a profit after tax of ` <font color='green'>1,455.36</font> ` lakhs...\n"
      f"here is the input report from LLM {input_text}"
    )

    model_name = "gemini-2.0-flash"
    response_text = await run_sync_in_thread(_sync_generate_content, model_name, prompt4)
    return response_text



async def checker(input_text):
    prompt3 = (
    "You are a Checker LLM. Your task is to evaluate the output from another LLM related to Finance or financial summaries. "
    "if the document doesn't contain financial information , you should return a message saying 'Wrong' "
    "Respond strictly with one word: either 'RIGHT' or 'WRONG'. Do not include any additional words, explanations, or punctuation.\n\n"

    "Respond with 'WRONG' if any of the following are true:\n"
    "- Do NOT use code blocks such as ``` or ```html. These are strictly prohibited.\n"
    "Strictly No HTML or markdown Code Blocks: Under no circumstances should the output include ```html or any kind of code block formatting. This is strictly prohibited and must be avoided at all costs."
    "- The input contains error messages, apologies, or phrases like 'Unable to generate', 'I am unable to', '[ERROR]', or indicates missing data.\n"
    "- The input includes conversational or assistant-style language such as: Here's the company insight report based on the provided financial data\n"
    "  'Okay now I understand', 'Sure! Here's an improved version', 'Let me know if', 'Here is the generated summary', "
    "'Sure! Here's the grammatically correct version', or any similar interactive phrases.\n"
    "- The input contains gibberish like 'fmhgbdlmbhdf' or similar non-sensical strings.\n"
    "= if response contain **```html** then response should be WRONG"
    "- The input includes the backtick character (`), such as in (`<font color='green'>1,455.36</font>`).\n\n"
    "Respond with 'RIGHT' only if the input is a complete, accurate, and valid financial summary with no conversational tone or formatting issues.\n"
    "For example, (<font color='green'>1,455.36</font>) is acceptable and should be marked as 'RIGHT'.\n\n"
    "If Input has too much of an empty space such as multiple blank lines, it should be marked as 'WRONG'.\n\n"
    "- **Avoid Multiple empty lines:** Do not print multiple empty lines and not also  ----------------------------------------- lines like this if it is in inpur return WRONG\n"

    "Try to generate whole as given below format and **if it is half generated or not in proper markdown response will be 'WRONG'** \n\n"
    "**Output Format:**\n"
    "# 📊 [Company Name] Overview\n"
    "## 💰 Summary\n"
   
    "## 💰 Financial Health\n"
    
    "## 📈 Investment Insights\n"
   
    "## 📊 Key Financial Metrics\n"
    "| 📌 Metric | 📉 Value | 📋 Explanation |\n"
    "|----------|---------|---------------|\n"
    
    "## 📊 Comparative Analysis\n"
    
    "## 🔮 Predictive Analysis\n"
    "| 🔍 Metric | 📈 Last Reported Value | 📊 Forecasted Next Value | 🔎 Prediction Rationale |\n"
    "|----------|----------------------|----------------------|----------------------|\n"
    "[For each available financial metric (e.g., revenue, net profit, EPS, debt levels, and all possible predictions), predict the next logical data point based on historical trends, growth patterns, and financial ratios. Provide a detailed explanation for each prediction.]\n\n"
    "add the following line at the end of each report 'This report is for informational purposes only and should not be considered as investment advice. Investors should conduct their own research and consult with a financial advisor before making investment decisions'"

    f"Here is the original report:\n{input_text}"
    )
    model_name = "gemini-2.0-flash"
    response_text = await run_sync_in_thread(_sync_generate_content, model_name, prompt3)
    return response_text